In [1]:
#import libraries

import pandas as pd
import os
from sklearn.metrics import confusion_matrix

In [2]:
link_to_data = 'https://raw.githubusercontent.com/SIT719/2020-S2/master/data/payment_fraud.csv'
dfp = pd.read_csv(link_to_data, error_bad_lines=False)

In [3]:
dfp

,accountAgeDays,numItems,localTime,paymentMethod,paymentMethodAgeDays,label
0,29,1,4.745402,paypal,28.204861,0
1,725,1,4.742303,storecredit,0.000000,0
2,845,1,4.921318,creditcard,0.000000,0
3,503,1,4.886641,creditcard,0.000000,0
4,2000,1,5.040929,creditcard,0.000000,0
5,119,1,4.962055,paypal,0.000000,0
6,2000,1,4.921349,paypal,0.000000,0
7,371,1,4.876771,creditcard,0.000000,0
8,2000,1,4.748314,creditcard,0.000000,0
9,4,1,4.461622,creditcard,0.000000,0
10,26,1,4.745402,paypal,0.000000,0
11,2000,1,4.505662,creditcard,0.000694,0
12,3,1,4.962055,creditcard,2.690972,0
13,3,1,4.921318,creditcard,2.069444,0
14,23,1,4.745402,creditcard,0.001389,0
15,5,1,4.921349,paypal,4.036111,0
16,1208,1,4.836982,creditcard,0.000694,0
17,11,1,4.921349,creditcard,10.865972,0
18,123,1,4.748314,creditcard,0.000694,0
19,2000,1,4.895263,creditcard,248.774306,0
20,1672,1,5.034622,creditcard,978.752778,0
21,36,1,4.742303,creditcard,0.014583,0
22,16,1,4.886641,creditcard,15.796528,0
23,278,1,5.034622,creditcard,6.892361,0
24,223,1,4.748314,creditcard,0.000000,0
25,30,1,4.057414,creditcard,0.000000,0
26,2,1,4.921349,creditcard,0.000000,0
27,2000,1,3.483951,creditcard,503.425000,0
28,1936,1,4.057414,creditcard,635.641667,0
29,2000,1,4.921318,creditcard,948.806944,0
...,...,...,...,...,...,...
39191,137,1,4.461622,creditcard,136.703472,0
39192,2000,1,4.876771,creditcard,0.000000,0
39193,156,1,4.886641,paypal,91.781944,0
39194,225,1,4.461622,creditcard,0.000000,0
39195,1631,1,4.876771,creditcard,0.000000,0
39196,491,1,4.921318,creditcard,22.220833,0
39197,490,1,4.748314,creditcard,0.005556,0
39198,83,1,4.057414,paypal,82.795139,0
39199,150,1,4.895263,creditcard,149.981944,0
39200,936,1,4.745402,creditcard,1.772917,0
39201,84,1,4.895263,creditcard,83.018056,0
39202,124,1,4.524580,creditcard,123.047917,0
39203,131,1,4.921318,creditcard,0.000000,0
39204,192,1,2.948940,creditcard,181.184722,0
39205,241,1,5.017904,paypal,0.000000,0
39206,1116,1,4.895263,creditcard,0.000000,0
39207,2000,1,4.921349,creditcard,410.779167,0
39208,508,1,4.748314,creditcard,357.716667,0
39209,629,1,4.876771,creditcard,258.222222,0
39210,1607,1,4.886641,creditcard,0.000000,0
39211,2000,1,4.886641,creditcard,0.000000,0
39212,2000,1,5.040929,creditcard,185.286806,0
39213,108,1,4.748314,creditcard,48.965278,0
39214,101,2,4.524580,storecredit,100.746528,0
39215,1257,1,4.965339,creditcard,813.097222,0
39216,986,1,4.836982,creditcard,0.000000,0
39217,1647,1,4.876771,creditcard,377.930556,0
39218,1591,1,4.742303,creditcard,0.000000,0
39219,237,1,4.921318,creditcard,236.082639,0
39220,272,1,5.040929,paypal,0.000694,0

In [4]:
df = pd.get_dummies(dfp, columns=['paymentMethod'])

In [5]:
df

,accountAgeDays,numItems,localTime,paymentMethodAgeDays,label,paymentMethod_creditcard,paymentMethod_paypal,paymentMethod_storecredit
0,29,1,4.745402,28.204861,0,0,1,0
1,725,1,4.742303,0.000000,0,0,0,1
2,845,1,4.921318,0.000000,0,1,0,0
3,503,1,4.886641,0.000000,0,1,0,0
4,2000,1,5.040929,0.000000,0,1,0,0
5,119,1,4.962055,0.000000,0,0,1,0
6,2000,1,4.921349,0.000000,0,0,1,0
7,371,1,4.876771,0.000000,0,1,0,0
8,2000,1,4.748314,0.000000,0,1,0,0
9,4,1,4.461622,0.000000,0,1,0,0
10,26,1,4.745402,0.000000,0,0,1,0
11,2000,1,4.505662,0.000694,0,1,0,0
12,3,1,4.962055,2.690972,0,1,0,0
13,3,1,4.921318,2.069444,0,1,0,0
14,23,1,4.745402,0.001389,0,1,0,0
15,5,1,4.921349,4.036111,0,0,1,0
16,1208,1,4.836982,0.000694,0,1,0,0
17,11,1,4.921349,10.865972,0,1,0,0
18,123,1,4.748314,0.000694,0,1,0,0
19,2000,1,4.895263,248.774306,0,1,0,0
20,1672,1,5.034622,978.752778,0,1,0,0
21,36,1,4.742303,0.014583,0,1,0,0
22,16,1,4.886641,15.796528,0,1,0,0
23,278,1,5.034622,6.892361,0,1,0,0
24,223,1,4.748314,0.000000,0,1,0,0
25,30,1,4.057414,0.000000,0,1,0,0
26,2,1,4.921349,0.000000,0,1,0,0
27,2000,1,3.483951,503.425000,0,1,0,0
28,1936,1,4.057414,635.641667,0,1,0,0
29,2000,1,4.921318,948.806944,0,1,0,0
...,...,...,...,...,...,...,...,...
39191,137,1,4.461622,136.703472,0,1,0,0
39192,2000,1,4.876771,0.000000,0,1,0,0
39193,156,1,4.886641,91.781944,0,0,1,0
39194,225,1,4.461622,0.000000,0,1,0,0
39195,1631,1,4.876771,0.000000,0,1,0,0
39196,491,1,4.921318,22.220833,0,1,0,0
39197,490,1,4.748314,0.005556,0,1,0,0
39198,83,1,4.057414,82.795139,0,0,1,0
39199,150,1,4.895263,149.981944,0,1,0,0
39200,936,1,4.745402,1.772917,0,1,0,0
39201,84,1,4.895263,83.018056,0,1,0,0
39202,124,1,4.524580,123.047917,0,1,0,0
39203,131,1,4.921318,0.000000,0,1,0,0
39204,192,1,2.948940,181.184722,0,1,0,0
39205,241,1,5.017904,0.000000,0,0,1,0
39206,1116,1,4.895263,0.000000,0,1,0,0
39207,2000,1,4.921349,410.779167,0,1,0,0
39208,508,1,4.748314,357.716667,0,1,0,0
39209,629,1,4.876771,258.222222,0,1,0,0
39210,1607,1,4.886641,0.000000,0,1,0,0
39211,2000,1,4.886641,0.000000,0,1,0,0
39212,2000,1,5.040929,185.286806,0,1,0,0
39213,108,1,4.748314,48.965278,0,1,0,0
39214,101,2,4.524580,100.746528,0,0,0,1
39215,1257,1,4.965339,813.097222,0,1,0,0
39216,986,1,4.836982,0.000000,0,1,0,0
39217,1647,1,4.876771,377.930556,0,1,0,0
39218,1591,1,4.742303,0.000000,0,1,0,0
39219,237,1,4.921318,236.082639,0,1,0,0
39220,272,1,5.040929,0.000694,0,0,1,0

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('label', axis=1), df['label'],
    test_size=0.33, random_state=17)

In [8]:
X_train

,accountAgeDays,numItems,localTime,paymentMethodAgeDays,paymentMethod_creditcard,paymentMethod_paypal,paymentMethod_storecredit
13272,4,1,4.886641,0.000000,1,0,0
22716,1554,1,4.461622,0.256944,0,0,1
30255,2,1,4.742303,1.840278,1,0,0
7676,2000,1,4.748314,0.584028,1,0,0
15105,157,1,5.017904,156.022222,1,0,0
31782,644,1,4.895263,1.568056,0,0,1
33547,100,1,5.017904,0.000000,0,1,0
9009,260,1,5.034622,259.775000,0,1,0
16172,1213,3,5.040929,0.013194,1,0,0
22553,892,1,4.921349,97.968750,0,1,0
35976,337,1,4.921318,0.000000,0,1,0
17282,1903,1,4.836982,0.000694,1,0,0
24434,889,1,4.745402,0.000000,0,1,0
14254,4,1,4.962055,0.001389,0,1,0
13591,579,1,4.921318,0.000000,1,0,0
3822,77,1,4.836982,0.000000,0,1,0
12972,204,1,4.962055,73.897917,1,0,0
29868,1016,1,4.921318,0.000000,0,1,0
38599,127,1,5.034622,41.326389,1,0,0
17640,7,1,4.921318,4.133333,1,0,0
15671,1941,1,4.748314,2.820833,1,0,0
4399,2000,1,4.505662,674.019444,1,0,0
10136,1459,1,4.836982,100.588194,1,0,0
32326,919,1,5.017904,0.000000,1,0,0
21101,580,5,4.895263,91.688889,1,0,0
34233,2000,1,4.748314,0.002083,0,1,0
27831,563,1,4.461622,0.000000,1,0,0
29159,2000,1,4.886641,356.706944,0,0,1
9164,2000,1,4.524580,0.000000,1,0,0
28458,39,1,4.524580,38.020833,1,0,0
...,...,...,...,...,...,...,...
17434,2000,1,4.745402,0.009722,0,1,0
10199,1386,1,4.524580,0.000000,0,1,0
20347,210,1,4.876771,179.807639,0,1,0
29682,40,1,3.954522,0.000000,1,0,0
18715,1701,1,4.921349,0.002083,0,1,0
19464,559,1,4.057414,1.003472,1,0,0
12665,143,1,4.921318,0.000000,0,1,0
15409,539,1,4.057414,6.044444,0,1,0
4379,27,1,5.040929,0.000694,1,0,0
19000,1,1,4.742303,0.000000,0,1,0
23929,4,1,4.921318,3.215972,1,0,0
3116,13,2,4.895263,0.000694,0,0,1
5122,2,1,4.876771,0.000000,0,1,0
2877,4,2,5.017904,3.246528,1,0,0
34848,135,1,4.895263,0.000000,1,0,0
37870,1,1,4.836982,0.000000,0,1,0
3345,3,1,4.965339,2.904861,1,0,0
21177,459,1,4.886641,0.000000,1,0,0
1833,115,1,4.836982,114.260417,1,0,0
7334,510,1,5.017904,0.006944,1,0,0
5763,1637,1,4.921318,154.180556,1,0,0
19210,320,1,4.745402,0.000000,1,0,0
1774,2000,1,4.965339,0.000000,1,0,0
14252,937,1,4.836982,173.538889,0,0,1
37332,1631,1,4.962055,0.004861,1,0,0
31044,2000,1,4.921349,0.000000,0,1,0
25631,47,1,4.962055,0.000000,1,0,0
33174,2000,1,4.748314,0.000000,1,0,0
34959,82,1,4.745402,0.000000,1,0,0
10863,481,1,4.965339,0.000000,1,0,0

In [9]:
y_train

13272    0
22716    0
30255    0
7676     0
15105    0
31782    0
33547    0
9009     0
16172    0
22553    0
35976    0
17282    0
24434    0
14254    0
13591    0
3822     0
12972    0
29868    0
38599    0
17640    0
15671    0
4399     0
10136    0
32326    0
21101    0
34233    0
27831    0
29159    0
9164     0
28458    0
        ..
17434    0
10199    0
20347    0
29682    0
18715    0
19464    0
12665    0
15409    0
4379     0
19000    1
23929    0
3116     0
5122     0
2877     0
34848    0
37870    1
3345     0
21177    0
1833     0
7334     0
5763     0
19210    0
1774     0
14252    0
37332    0
31044    0
25631    0
33174    0
34959    0
10863    0
Name: label, Length: 26278, dtype: int64

In [10]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)

c:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [11]:
y_pred = clf.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score

In [13]:
print(accuracy_score(y_pred, y_test))

0.999922738159623

In [14]:
print(confusion_matrix(y_test, y_pred))

[[12753     0]
 [    1   189]]